
# Name of Our Workflow
  name:React CI/CD Pipeline
# Trigger the work flow on push to main
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest


  setps:
     - name: Checkout code
       uses: actions/checkout@v2


     - name: Set Up Node.js
       uses: actions/setup-node@2
       with:
         node-version:'20'


     - name: install Dependency
       run: npm install

     - name: Run Test
       run: npm test

     - name: Build project
       run: npm run build